### ISSUE TITLE
Only updates MIT but `new` can generate from many licenses

### ISSUE THREAD

**Issue by phated** [update/updater-license#3]
When running `update license:new`, you are prompted to choose a license.  If you choose anything other than MIT, the updater won't work on next run.

**Comment by jonschlinkert** [comment]
as I recall most of the licenses don't actually have any metadata that needs to be updated (I might be wrong about that, I'll need to double-check).  We've talked about adding support for others though, I think it makes sense if we can parse and re-render them reliably.
